### ISSUE TITLE
Missing import 'graph_reader'

### ISSUE THREAD

**Issue by dlingcmu** [dongguanting/SKP-for-KBQA#1]
Hi, thanks for sharing this great idea. I am trying to reproduce the results using this repo, but I have a problem when running the 'webqsp_preprocess.py', I found there is an import for graph_reader. May I ask what is this graph_reader? I can not simply install it through pip. Thanks~

**Comment by Fragile-hue** [comment]
Have you found the  'webqsp_preprocess.py' file?

**Comment by Fragile-hue** [comment]
Have you found the graph_reader module in  'webqsp_preprocess.py' file?
